### ISSUE TITLE
Review de mallorie sur le site SPYRALS 

### ISSUE THREAD

**Issue by Nul0s** [Spyrals-IO/Spyrals-io.github.io#1]
-Sur la version mobile : 
-Spyrals n'est pas écrit en furore
-Le linging du carré decouvrir notre offre est trop important
-Les couleurs du nous écrire et voir la video ne sont pas les bonnes
-Le texte du bouton nous écrire doit être remplacé par contact et voir la vidéo par video. 
-Le contact et la video doivent être sur le coté gauche et rester tout le long du scroll, ils peuvent être déroulés au début puis se reouler sur eux même pour ne former qu'un logo. Ou etre symbolisés par des logos. 

-Le ligning des photos doit être dégradé en gradient vers le centre de la page. Le ton doit être plus foncé pour celui en violet vif rosé. 
-Je ne comprend pas pourquoi le footer est aussi gros et séparé par une barre violet ( perso jsuis pas trop fan ). 
-Les émoticons FB LINK doivent être hexagonales
-ID on pourrait mettre le logo en plus petit et réduire le heade qui me parait trop grand. D'ailleur l'écran me semble long meme avec du scroll. Le header me parait grand. 
-On pourrait meme mettre le logo a la place de Spyrals écrit ?
-Je trouve que le système de retour est pas efficace et pas positif, il faudrait peut être un truc plus en temps réel. JM pas critiquer comme ca :( pardon l'équipe. 

-Le fait de mettre fiere d'être herbegé par git, je trouve que ca fait pas sérieux, personnelement. PS le lien par contre est super cool c'est vous qui l'avez fait ? 
-Quelle est la police utilisé pour le contact et l'offre ect, on pourrait tester furor

-Sur la version web 
-Pareil pour le footer
-Les couleurs
-Les dégradés des lining
-Il faut remplacer l'offre par Nos services
-Le ligning jaune autour de decouvrir notre offre est trop épais, = pour nous contacter
-La version optimisée est pas carrée ( cheloue, écran réduit).
-Les icones FB & co doivent être hexagonales
-Les logos des clients sont trop gros
-Le 06 doit etre sur une ligne
-Pourquoi cette ligne de spéaration avec le footer ( sinon ont peu la faire mais d'une autre couleur moins flash ( genre bleu nuit, ou bleu ou violet puissant ?

**Comment by thibautwormkil** [comment]
From discord 

Merlin — Aujourd’hui à 14:26
- La police j'imagine que c'est juste qu'il a était vite coté maquette mais on garde evidemment la même 
- Les ligning ? Tu parles des bordures ?
- Je n'ai pas vu de dégradé dans la maquette
- L'épaisseur est d'un px en plus en que sur la maquette, je trouvais ça mieux sur ordi mais on peut la mettre à 2 (elle est à 4) sur le mobile oui.
- La photo on l'enlève, sur dekstop la bordure est de 4 au lieu de 3 dans la maquette, à ma demande.
- En quoi le footer est mal sizé ? On prend la taille de la maquette ^^
- "Le spyrals" Logo ? Mot ? A priori le placement est basé sur les maquette. Tu penses que sur mobile ça devrait être déplacé ?
- Emoticone pas celle de base => jules ne nous a pas donné les svg, fabien à fait de son mieux.
- lignes arrondis ? Lesquels ?


Merlin — Aujourd’hui à 14:51
J'ai répondus au plus gros déjà donc je prend les points restants un par un :
 - mettre les boutons sur le coté ça ne me semble pas bien pratique niveau lecture. Après ils vont tout de même suivre le scroll. On pourrait les agrandir pour en faire deux boutons complets ? Pas sûr de cette proposition non-plus.

Niveau couleurs ce sont celle de la maquette. On peut les changer facilement mais ce sont celle que l'on a eu.

La barre du footer, la barre violette ? 

T'aime pas mon "fière d'être ..." ? Pourquoi ? C'est un détail technique assez étrange, personne ne fait ça et pour ceux qui savent ça renforce notre positionnement tech, tout en donnant accès au code du site pour faire du SEO.

Je peux être d'accord que les logo de la parties ancien clients sont un peu gros.

Pour les changements de textes on peut faire ça a la fin 🙂

**Comment by thibautwormkil** [comment]
@Nul0s @Methrat0n 

## Version Mobile
1.  **Mallorie** :  Spyrals n'est pas écrit en furore
**Merlin** : La police j'imagine que c'est juste qu'il a était vite coté maquette mais on garde evidemment la même
**Thibaut** : J'ai récupéré la maquette importé sur Lunacy pour gagner du temps sur la maquette, la police a été perdu durant le processus mais oui évidément on garde le même :) 

2.  **Mallorie** :  Le linging du carré decouvrir notre offre est trop important
**Merlin** : Les ligning ? Tu parles des bordures ?
**Thibaut** : Pareil récupéré de l'importation, la version web est/sera la version retenu, pas celle que je montre dans les brouillons rapides.

3.  **Mallorie** :  Les couleurs du nous écrire et voir la video ne sont pas les bonnes
**Merlin** : 
**Thibaut** : Pareil récupéré de l'importation, la version web est/sera la version retenu, pas celle que je montre dans les brouillons rapides.

4.  **Mallorie** :  Le texte du bouton nous écrire doit être remplacé par contact et voir la vidéo par video.
**Merlin** : 
**Thibaut** : Ajouté au TODO Fabien

5.  **Mallorie** :  Le contact et la video doivent être sur le coté gauche et rester tout le long du scroll, ils peuvent être déroulés au début puis se reouler sur eux même pour ne former qu'un logo. Ou etre symbolisés par des logos.
**Merlin** : Mettre les boutons sur le coté ça ne me semble pas bien pratique niveau lecture. Après ils vont tout de même suivre le scroll. On pourrait les agrandir pour en faire deux boutons complets ? Pas sûr de cette proposition non-plus.
Niveau couleurs ce sont celle de la maquette. On peut les changer facilement mais ce sont celle que l'on a eu.
**Thibaut** : J'ai peur que sa prennent pas mal de place sur le côté de la version mobile mais je vais faire une version pour testé sa, ajouté a mon TODO :) Par contre je ne comprend pas quand ils sont déroulés et quand ils se réenroulent ? Tu parle de 'au début' mais je ne vois pas trop de quand tu parle :(

6.  **Mallorie** : Le ligning des photos doit être dégradé en gradient vers le centre de la page. Le ton doit être plus foncé pour celui en violet vif rosé.
**Merlin** : _(from thibaut : je sais pas trop ou mettre tout sa :( )_
Je n'ai pas vu de dégradé dans la maquette
L'épaisseur est d'un px en plus en que sur la maquette, je trouvais ça mieux sur ordi mais on peut la mettre à 2 (elle est à 4) sur le mobile oui.
La photo on l'enlève, sur dekstop la bordure est de 4 au lieu de 3 dans la maquette, à ma demande.
**Thibaut** : Pareil récupéré de l'importation, la version web est/sera la version retenu, pas celle que je montre dans les brouillons rapides :) De plus je considère que les photos ne seront pas présent sur la page mobile suite au souhait de merlin.


7.  **Mallorie** : Je ne comprend pas pourquoi le footer est aussi gros et séparé par une barre violet ( perso jsuis pas trop fan ).
**Merlin** : En quoi le footer est mal sizé ? On prend la taille de la maquette ^^
La barre du footer, la barre violette ?
**Thibaut** : J'ai positionné rapidement les éléments et c'est vrai que je perd pas mal de place. Je vais faire une version plus détaillé pour testé sa (mit dans mon todo). La barre violette est reprise de l'importation de la maquette sur Lunacy. La version web est/sera la version retenu. 

8.  **Mallorie** : Les émoticons FB LINK doivent être hexagonales
**Merlin** : Emoticone pas celle de base => jules ne nous a pas donné les svg, fabien à fait de son mieux.
**Thibaut** : Bah normalement elle le sont, en tout cas ce que j'ai récupéré de l'importation été hexagonale :) La version web est/sera la version retenu de toute façon :)

9.  **Mallorie** : ID on pourrait mettre le logo en plus petit et réduire le heade qui me parait trop grand. D'ailleur l'écran me semble long meme avec du scroll. Le header me parait grand.
**Merlin** : 
**Thibaut** : My bad sur la photo que j'ai transmise j'avais pas encore mit la ligne rouge donc on se rend pas vraiment compte de la taille de l'écran. La version actuelle possède la ligne. 
J'ai fais le header rapidement pour le brouillon mais je peux faire une version plus petite si besoin :) 

10.  **Mallorie** : On pourrait meme mettre le logo a la place de Spyrals écrit ?
**Merlin** : "Le spyrals" Logo ? Mot ? A priori le placement est basé sur les maquette. Tu penses que sur mobile ça devrait être déplacé ?
**Thibaut** : J'ai récupéré la même logique que celui des maquettes pour réduire les coûts à l'importation, hormis la taille de la police. Je vais faire une v test rapidement pour voir ce que sa donne avec le Logo à la place du Titre.

11.  **Mallorie** : Je trouve que le système de retour est pas efficace et pas positif, il faudrait peut être un truc plus en temps réel. JM pas critiquer comme ca :( pardon l'équipe.
**Merlin** : 
**Thibaut** : Je pense que quand il n'y a que 2 ou 3 retour a faire, on peut se permettre de faire ça en temps réel mais quand y'a beaucoup de retour, je pense que c'est mieux de pouvoir le faire en différé. 
Et je pense que pouvoir critiqué le mal comme le bien est sain. La personne qui reçoit les critiques et les retours doit comprendre que c'est pour le bien de Spyrals et souvent les solutions les meilleurs sont des compromis d'idée original :)

12.  **Mallorie** : Le fait de mettre fiere d'être herbegé par git, je trouve que ca fait pas sérieux, personnelement. PS le lien par contre est super cool c'est vous qui l'avez fait ?
**Merlin** : T'aime pas mon "fière d'être ..." ? Pourquoi ? C'est un détail technique assez étrange, personne ne fait ça et pour ceux qui savent ça renforce notre positionnement tech, tout en donnant accès au code du site pour faire du SEO.
**Thibaut** : On pourrait juste indiqué 'Hébergé par ' + [Logo Github]. Notre fierté est sous-entendu par la mention de l'hébergement. Vous en pensez quoi ? 

13.  **Mallorie** : Quelle est la police utilisé pour le contact et l'offre ect, on pourrait tester furor
**Merlin** : 
**Thibaut** : J'ai pas choisi et juste récupéré ce que j'ai pu de la maquette, je pense qu'il faudrait voir sa directement sur la version web, mais je peux faire une v test rapidement si vous voulez :) 


## Version Mobile
Je ne suis pas taché sur l'implémentation de la v web donc je ne vais pas répondre au autre retour, renvoyant la balle à @Nul0s @Methrat0n @Fabfr0st pour voir ce que vous voulez changé sur la v web :)


## Récap des TODO 
TODO @Fabfr0st :
- Les bouton 'Nous écrire' et 'Voir la vidéo' devienne respectivement : "Contact" & "Vidéo"
(From Merlin : Pour les changements de textes on peut faire ça a la fin 🙂 )

TODO @thibautwormkil 
- Faire une v test pour la v mobile de la bannière fixe, mise sur le côté, voir juste en logo, voir animation ?
- Réduire plus précisément la taille du footer de la v mobile.
- Faire une v test avec Titre Spyrals remplacé par le logo.
